### PR TITLE
Fixes reference to lombok and Basic implementation of Post class

### LINKED ISSUE #4: Create Post Class
{
    id: number,
    link: string,
    modified: Date,
    type: string,
    title: string,
    content: string,
    authorId: number,
    featuredMediaId: number,
    categoryIds: number[],
    tagIds: number[],
    thumbnailImage: string
}

### PR DESCRIPTION
**Pull request by davefeucht**

### CODE REVIEW

File: photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+import lombok.Setter;
+
+@Getter @Setter @NoArgsConstructor
+/**
+ * Represents a Post of the CMS
+ */
+public class Post {
+    private int id;
+    /** Date/Time Post was last modified */
+    private String modified;
```
Comment (eoikonomou) [inline photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java]: It's better to be a `Date`

File: photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java [hunk 2]
```diff
@@ -0,0 +1,81 @@
+package com.throughapinhole.photoportfolio.Classes;
+
+import java.util.ArrayList;
+
+import lombok.Getter;
+import lombok.NoArgsConstructor;
+import lombok.Setter;
+
+@Getter @Setter @NoArgsConstructor
```
Comment (eoikonomou) [inline photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java]: Best to have one annotation per line just to make things clearer

File: photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java [hunk 3]
```diff
@@ -0,0 +1,81 @@
+package com.throughapinhole.photoportfolio.Classes;
```
Comment (eoikonomou) [inline photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java]: The convention is usually that you create an `Entity` for things that get into the database and a `DTO` that you send back to the client. This is an entity so I think it's best to have it in a `entities` package. `com.throughapinhole.photoportfolio.entities`. Also we usually don't create uppercase package names.

File: photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+    /** Text title of Post */
+    private String title;
+    /** Text content of Post */
+    private String content;
+    /** User ID of author of Post */
+    private int author;
+    /** Media ID of featured Media of Post */
+    private int featuredMedia;
+    /** List of Category IDs assigned to the Post */
+    private ArrayList<Integer> categories;
```
Comment (eoikonomou) [inline photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java]: This should probably be `categoryIds` right?

File: photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java [hunk 5]
```diff
@@ -0,0 +1,81 @@
...
+    /** Type of Post */
+    private String type;
+    /** Text title of Post */
+    private String title;
+    /** Text content of Post */
+    private String content;
+    /** User ID of author of Post */
+    private int author;
+    /** Media ID of featured Media of Post */
+    private int featuredMedia;
```
Comment (eoikonomou) [inline photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java]: Same here

File: photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java [hunk 6]
```diff
@@ -0,0 +1,81 @@
...
+    /** Date/Time Post was last modified */
+    private String modified;
+    /** Type of Post */
+    private String type;
+    /** Text title of Post */
+    private String title;
+    /** Text content of Post */
+    private String content;
+    /** User ID of author of Post */
+    private int author;
```
Comment (eoikonomou) [inline photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java]: And here

File: photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java [hunk 7]
```diff
@@ -0,0 +1,81 @@
...
+    /** Media ID of featured Media of Post */
+    private int featuredMedia;
+    /** List of Category IDs assigned to the Post */
+    private ArrayList<Integer> categories;
+    /** List of Tag IDs assigned to the Post */
+    private ArrayList<Integer> tags;
```
Comment (eoikonomou) [inline photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java]: here as well

File: photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java [hunk 8]
```diff
@@ -0,0 +1,81 @@
...
+        this.title = title;
+        this.content = content;
+        this.author = author;
+    }
+
+    /**
+     * Adds a Category ID to the list of Categories for the Post
+     * @param categoryId Category ID of the Category to add
+     */
+    public void addCategory(int categoryId) {
```
Comment (eoikonomou) [inline photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java]: These methods don't make sense 100% btw unless you have a reason to make small changes in the entity. I would expect you to send the whole thing from a frontend (maybe a custom CMS or from the actual frontend web app) instead of having to communicate back and forth with the backend to update small parts of the entity.

File: photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java (hunk 3 above)
Comment (davefeucht) [reply photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java]: Ok, sounds good. I'll change the file structure around a bit.

File: photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java (hunk 8 above)
Comment (davefeucht) [reply photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java]: Ok, I will maybe leave them for now, and we can discuss the general flow and see if we want to remove them then.

File: photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java (hunk 1 above)
Comment (davefeucht) [reply photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java]: Done

File: photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java (hunk 2 above)
Comment (davefeucht) [reply photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java]: Done

File: photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java (hunk 3 above)
Comment (davefeucht) [reply photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java]: Done - changed 'Classes' to 'entities'

File: photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java (hunk 4 above)
Comment (davefeucht) [reply photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java]: Changed all these namings to indicate they are Ids

File: photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java (hunk 3 above)
Comment (davefeucht) [reply photo-portfolio/src/main/java/com/throughapinhole/photoportfolio/Classes/Post.java]: Merged your first branch also and re-arranged things in my two branches to match.

**Review by eoikonomou — APPROVED** [review]
